#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <string>

#include "virtual_planner/infrastructure/postgres/postgres_config.hpp"
#include "virtual_planner/infrastructure/postgres/postgres_database.hpp"
#include "virtual_planner/infrastructure/postgres/postgres_user_repository.hpp"

#include "support/expect.hpp"

using namespace virtual_planner;

namespace
{

bool has_postgres_environment()
{
    return std::getenv("POSTGRES_DB") != nullptr &&
           std::getenv("POSTGRES_USER") != nullptr &&
           std::getenv("POSTGRES_PASSWORD") != nullptr;
}

// O usuario semeado pela migration 001. Existe para que as foreign keys de
// goals, tasks e reminders tenham para onde apontar, e nao pode ser removido
// por este teste: apagar a linha 1 derrubaria dados dos outros modulos.
constexpr std::uint64_t kSeededUser = 1;

// E-mail exclusivo deste teste. `users_email_unique_idx` (migration 052) rejeita
// duplicata, entao reaproveitar um endereco entre execucoes faria a segunda
// rodada falhar no create(). O dominio `.invalid` e reservado pela RFC 2606.
const std::string kEmail = "p26-4-integration@local.invalid";
const std::string kUpdatedEmail = "p26-4-integration-updated@local.invalid";

// Formato aceito por verifies_password() em auth_routes.cpp. O valor nao precisa
// derivar de senha real: o repositorio so o grava e le de volta.
const std::string kPasswordHash =
    "pbkdf2-sha256$1$00112233445566778899aabbccddeeff$00";

} // namespace

int main()
{
    using infrastructure::postgres::PostgresConfig;
    using infrastructure::postgres::PostgresDatabase;
    using infrastructure::postgres::PostgresUserRepository;

    if (!has_postgres_environment())
    {
        std::cout
            << "Skipping PostgreSQL user repository test: "
            << "POSTGRES_DB, POSTGRES_USER and POSTGRES_PASSWORD "
            << "are required.\n";

        return 0;
    }

    try
    {
        // Arrange
        PostgresDatabase database(
            PostgresConfig::from_environment());

        database.initialize();
        database.connect();

        PostgresUserRepository repository(database);

        // Uma execucao anterior interrompida antes do cleanup deixaria os
        // e-mails ocupados e o create() abaixo falharia por unicidade.
        for (const auto& leftover : repository.find_all())
        {
            if (leftover.email() == kEmail ||
                leftover.email() == kUpdatedEmail)
            {
                repository.remove(leftover.id());
            }
        }

        // Act: create()
        const domain::User novo{0, "Usuario de Integracao", kEmail};
        const auto id = repository.create(novo, kPasswordHash);

        // Assert create()
        VP_EXPECT(
            id != 0,
            "create() must return the identifier generated by the database");

        VP_EXPECT(
            id != kSeededUser,
            "create() must not reuse the seeded user id");

        // Assert find_by_id()
        const auto created = repository.find_by_id(id);

        VP_EXPECT(
            created.has_value(),
            "find_by_id() must find the user just created");

        VP_EXPECT(
            created->name() == "Usuario de Integracao",
            "find_by_id() must read back the persisted name");

        VP_EXPECT(
            created->email() == kEmail,
            "find_by_id() must read back the persisted email");

        // Assert find_credentials_by_email()
        const auto credentials =
            repository.find_credentials_by_email(kEmail);

        VP_EXPECT(
            credentials.has_value(),
            "find_credentials_by_email() must find the registered email");

        VP_EXPECT(
            credentials->user_id == id,
            "find_credentials_by_email() must return the matching user id");

        VP_EXPECT(
            credentials->password_hash == kPasswordHash,
            "find_credentials_by_email() must return the stored hash intact");

        // Act: save()
        domain::User alterado{id, "Usuario Renomeado", kUpdatedEmail};
        repository.save(alterado);

        // Assert save()
        const auto updated = repository.find_by_id(id);

        VP_EXPECT(
            updated.has_value(),
            "save() must keep the user retrievable");

        VP_EXPECT(
            updated->name() == "Usuario Renomeado",
            "save() must persist the new name");

        VP_EXPECT(
            updated->email() == kUpdatedEmail,
            "save() must persist the new email");

        // save() nao pode tocar na credencial: o caso de uso de perfil
        // (UpdateUserProfileUseCase) chama save() sem saber a senha, entao um
        // UPDATE que zerasse password_hash derrubaria o login do usuario.
        const auto credentials_after_save =
            repository.find_credentials_by_email(kUpdatedEmail);

        VP_EXPECT(
            credentials_after_save.has_value() &&
                credentials_after_save->password_hash == kPasswordHash,
            "save() must not overwrite the password hash");

        // Assert find_all()
        const auto all_users = repository.find_all();

        const auto contains = [&all_users](std::uint64_t wanted) {
            return std::any_of(
                all_users.begin(),
                all_users.end(),
                [wanted](const domain::User& current) {
                    return current.id() == wanted;
                });
        };

        VP_EXPECT(
            contains(id),
            "find_all() must include the created user");

        // O usuario semeado so e legivel porque a migration 052 preencheu name
        // e email nele. Sem esse backfill, montar domain::User a partir de NULL
        // lancaria excecao aqui.
        VP_EXPECT(
            contains(kSeededUser),
            "find_all() must include the seeded user from migration 001");

        // Cleanup
        repository.remove(id);

        VP_EXPECT(
            !repository.find_by_id(id).has_value(),
            "remove() must delete the user");

        VP_EXPECT(
            repository.find_by_id(kSeededUser).has_value(),
            "the seeded user must survive the test");

        database.shutdown();

        VP_EXPECT(
            !database.is_connected(),
            "database must be disconnected after shutdown");

        return 0;
    }
    catch (const std::exception& error)
    {
        std::cerr << error.what() << '\n';
        return 1;
    }
}
