-- Migration da faixa de Task (030-039, responsável: Bel).
--
-- ADR-002 (P-22A): o sistema é single-tenant. A tabela nasce com
--     user_id BIGINT NOT NULL REFERENCES users(id)
-- apontando para o usuário semeado em 001.
--
-- ADR-005 (P-26.2): o id é gerado pelo banco, como em goals e reminders.
-- GENERATED BY DEFAULT (e não ALWAYS) mantém válido um INSERT com id explícito
-- -- útil para carga de dados e para o teste de integração.
--
-- Agendamento por turno (P-18): o turno de uma tarefa é DERIVADO de
-- start_minutes (ReportingService::shift_of), não armazenado. Persistir
-- start_minutes e end_minutes fielmente é o que mantém o turno correto no
-- round-trip; não há coluna shift.
--
-- Colunas enum-like guardam exatamente as strings de domain::to_string()
-- (src/domain/enums/*.cpp); os CHECK impedem valor fora da camada C++.
-- Idempotência é responsabilidade do runner (schema_migrations); este arquivo
-- não usa IF NOT EXISTS, igual a 020 e 040.

CREATE TABLE tasks
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL REFERENCES users(id),

    description TEXT NOT NULL,

    category VARCHAR(50) NOT NULL,

    task_date DATE NOT NULL,

    start_minutes INTEGER NOT NULL,

    end_minutes INTEGER NOT NULL,

    priority VARCHAR(50) NOT NULL,

    status VARCHAR(50) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT tasks_category_check
    CHECK (category IN (
        'College',
        'Work',
        'Health',
        'Leisure',
        'PersonalProjects',
        'Study'
    )),

    CONSTRAINT tasks_priority_check
    CHECK (priority IN (
        'Low',
        'Medium',
        'High'
    )),

    CONSTRAINT tasks_status_check
    CHECK (status IN (
        'Pending',
        'Executed',
        'PartiallyExecuted',
        'Cancelled',
        'Postponed'
    )),

    -- Mesmos invariantes do value object TimeSlot: início não-negativo, fim
    -- depois do início e dentro do mesmo dia (24h = 1440 min).
    CONSTRAINT tasks_time_slot_check
    CHECK (start_minutes >= 0
       AND end_minutes > start_minutes
       AND end_minutes <= 1440)
);

-- Consulta natural do planner e do relatório: as tarefas de um dia -- e, por
-- start_minutes, o turno.
CREATE INDEX idx_tasks_user_date ON tasks (user_id, task_date);

-- Espelha idx_goals_status: filtro por status no relatório.
CREATE INDEX idx_tasks_status ON tasks (status);
