-- Issue #90: o id de reminders passa a ser gerado pelo banco, como ja
-- acontece em goals (BIGSERIAL desde 020_create_goals_table.sql).
--
-- Antes, `reminders.id` era um BIGINT PRIMARY KEY comum e o id vinha do
-- chamador, o que permitia que um INSERT ... ON CONFLICT DO UPDATE
-- sobrescrevesse silenciosamente um lembrete existente.
--
-- GENERATED BY DEFAULT (e nao ALWAYS) porque a coluna ja existe e um INSERT
-- com id explicito continua valido — util para carga de dados e para os
-- testes de integracao que precisam de um id conhecido.

ALTER TABLE reminders
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- A sequencia comeca em 1 por padrao. Se a tabela ja tiver linhas, o proximo
-- id geraria colisao de chave primaria; por isso a sequencia e reposicionada
-- acima do maior id existente. Em banco vazio o resultado e 1, igual ao
-- padrao.
SELECT setval(
    pg_get_serial_sequence('reminders', 'id'),
    COALESCE((SELECT MAX(id) FROM reminders), 0) + 1,
    false
);
